// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/uploader/upload.proto

package uploader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagem para os pedidos de upload (com o nome do arquivo e chunks de dados)
type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` // Nome do arquivo
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`       // Chunks de dados
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_proto_uploader_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uploader_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_uploader_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Mensagem para a resposta do upload
type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`  // Mensagem de status
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // Sucesso ou falha do upload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_uploader_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uploader_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_uploader_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_uploader_upload_proto protoreflect.FileDescriptor

const file_proto_uploader_upload_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/uploader/upload.proto\x12\buploader\"A\n" +
	"\rUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"D\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2M\n" +
	"\fFileUploader\x12=\n" +
	"\x06Upload\x12\x17.uploader.UploadRequest\x1a\x18.uploader.UploadResponse(\x01B\x19Z\x17proto/uploader;uploaderb\x06proto3"

var (
	file_proto_uploader_upload_proto_rawDescOnce sync.Once
	file_proto_uploader_upload_proto_rawDescData []byte
)

func file_proto_uploader_upload_proto_rawDescGZIP() []byte {
	file_proto_uploader_upload_proto_rawDescOnce.Do(func() {
		file_proto_uploader_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_uploader_upload_proto_rawDesc), len(file_proto_uploader_upload_proto_rawDesc)))
	})
	return file_proto_uploader_upload_proto_rawDescData
}

var file_proto_uploader_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_uploader_upload_proto_goTypes = []any{
	(*UploadRequest)(nil),  // 0: uploader.UploadRequest
	(*UploadResponse)(nil), // 1: uploader.UploadResponse
}
var file_proto_uploader_upload_proto_depIdxs = []int32{
	0, // 0: uploader.FileUploader.Upload:input_type -> uploader.UploadRequest
	1, // 1: uploader.FileUploader.Upload:output_type -> uploader.UploadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_uploader_upload_proto_init() }
func file_proto_uploader_upload_proto_init() {
	if File_proto_uploader_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_uploader_upload_proto_rawDesc), len(file_proto_uploader_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_uploader_upload_proto_goTypes,
		DependencyIndexes: file_proto_uploader_upload_proto_depIdxs,
		MessageInfos:      file_proto_uploader_upload_proto_msgTypes,
	}.Build()
	File_proto_uploader_upload_proto = out.File
	file_proto_uploader_upload_proto_goTypes = nil
	file_proto_uploader_upload_proto_depIdxs = nil
}
