// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/uploader/upload.proto

package uploader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileUploader_Upload_FullMethodName = "/uploader.FileUploader/Upload"
)

// FileUploaderClient is the client API for FileUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Definindo o serviço de upload de arquivos
type FileUploaderClient interface {
	// RPC para upload de arquivo em chunks
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error)
}

type fileUploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewFileUploaderClient(cc grpc.ClientConnInterface) FileUploaderClient {
	return &fileUploaderClient{cc}
}

func (c *fileUploaderClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileUploader_ServiceDesc.Streams[0], FileUploader_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileUploader_UploadClient = grpc.ClientStreamingClient[UploadRequest, UploadResponse]

// FileUploaderServer is the server API for FileUploader service.
// All implementations must embed UnimplementedFileUploaderServer
// for forward compatibility.
//
// Definindo o serviço de upload de arquivos
type FileUploaderServer interface {
	// RPC para upload de arquivo em chunks
	Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error
	mustEmbedUnimplementedFileUploaderServer()
}

// UnimplementedFileUploaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileUploaderServer struct{}

func (UnimplementedFileUploaderServer) Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedFileUploaderServer) mustEmbedUnimplementedFileUploaderServer() {}
func (UnimplementedFileUploaderServer) testEmbeddedByValue()                      {}

// UnsafeFileUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileUploaderServer will
// result in compilation errors.
type UnsafeFileUploaderServer interface {
	mustEmbedUnimplementedFileUploaderServer()
}

func RegisterFileUploaderServer(s grpc.ServiceRegistrar, srv FileUploaderServer) {
	// If the following call pancis, it indicates UnimplementedFileUploaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileUploader_ServiceDesc, srv)
}

func _FileUploader_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileUploaderServer).Upload(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileUploader_UploadServer = grpc.ClientStreamingServer[UploadRequest, UploadResponse]

// FileUploader_ServiceDesc is the grpc.ServiceDesc for FileUploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileUploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uploader.FileUploader",
	HandlerType: (*FileUploaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _FileUploader_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/uploader/upload.proto",
}
